version: '3.5'

services:
  quetzal-server-web:
    container_name: quetzal-server-web
    build:
      context: ./docker/nginx
      args:
        UID: $U_ID
    ports:
      - 80:80
    volumes:
      - ./public:/appdata/www/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - quetzal-be
    networks:
      - quetzal-network

  quetzal-be:
    container_name: quetzal-be
    build:
      context: docker/php
      args:
        UID: $U_ID
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    volumes:
      - ./:/appdata/www
      - ~/.ssh/id_rsa:/home/appuser/.ssh/id_rsa
    depends_on:
      - quetzal-db
    networks:
      - quetzal-network

  quetzal-db:
    container_name: quetzal-db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'quetzal-db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - quetzal-db:/var/lib/mysql
    networks:
      - quetzal-network

volumes:
  quetzal-db:

networks:
  quetzal-network:
    external: true